version: "2"
x-redash-service: &redash-service
 image: redash/redash:10.1.0.b50633
 depends_on:
    - postgres
    - redis
 env_file: /opt/redash/env
 restart: always
services:
 server:
    <<: *redash-service
    command: server
    ports:
     - "5000:5000"
    environment:
     REDASH_WEB_WORKERS: 4
 scheduler:
    <<: *redash-service
    command: scheduler
 scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
     QUEUES: "periodic,emails,default"
     WORKERS_COUNT: 1
 adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
     QUEUES: "queries,scheduled_queries,schemas"
     WORKERS_COUNT: 2
 redis:
    image: redis:6.2-alpine
    restart: always
 postgres:
    image: postgres:14.2-alpine
    env_file: /opt/redash/env
    volumes:
     - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always